-- TABLE OVERVIEW --
select * from menu_items m
join order_details o on o.item_id=m.menu_item_id;
SELECT COUNT(*) FROM menu_items;
SELECT COUNT(*) FROM order_details;
SELECT COUNT(DISTINCT order_id) FROM order_details;
/* Insight:
		1.The Restuarent Database contains two tables namely menu_items & Order_details
        2.The Menu Items Has totally 32 rows
        3.The Order_details has totally 12234 rows
        4.There are totally 5370 distinct items in the order_deatils table
*/
-- Total Revenue by Each Product --
select m.item_name,SUM(m.price) as Total_Revenue
from menu_items m
join order_details o on o.item_id=m.menu_item_id
group by m.item_name
order  by Total_Revenue desc;
 select m.item_name,SUM(m.price) as Total_Revenue
from menu_items m
join order_details o on o.item_id=m.menu_item_id
group by m.item_name
order by Total_Revenue DESC LIMIT 5;
-- Insight: Majority of revenue coming from the Korean Beef Bowl --



-- Average Revenue by Each Product --
select m.item_name,ROUND((AVG(m.price)),2) as  Average_Revenue
from menu_items m
join order_details o on o.item_id=m.menu_item_id
group by m.item_name
order by Average_Revenue desc,m.item_name;
-- Insight: Shrimp Scampi appears as the highest value item because it has the highest menu price, not necessarily because it sells more frequently-- 



-- Categorical Sales --
select m.category,COUNT(o.order_details_id) as order_count,SUM(m.price) as Total_Revenue,ROUND((Avg(m.price)),2) as Average_Revenue from menu_items m
join order_details o on o.item_id=m.menu_item_id
group by m.category
order by Total_Revenue desc;
/* Insight: 
        1.Most of the revenue is being generated from the Italian Food items with 2948 orders which is making the Italian food as an Expensive Category 
		2.The Asian Food Items stands at the second place as a revenue generator with higher sales rate than the italian food items and this concludes that the ASIAN FOOD ITEMS are Budget-Freindly Food Items
        */


-- MONTHLY SALES --
select month(o.order_date) as monthly_sales,SUM(m.price) as Monthly_Revenue from menu_items m
join order_details o on o.item_id=m.menu_item_id
group by monthly_sales;

with cte as (
select DATE_FORMAT(o.order_date,'%Y-%m') as monthly_sales,m.category as Food_category,SUM(m.price) as Monthly_Revenue 
from menu_items m
join order_details o on o.item_id=m.menu_item_id
group by monthly_sales,m.category),
cas as (
 select monthly_sales,Food_category,Monthly_Revenue ,row_number()over(partition by monthly_sales order by monthly_revenue desc) as rn
 from cte
 )
 select  monthly_sales,Food_category,Monthly_Revenue
 from cas
 where rn<=2;
 -- Insight: In Every Month the ITALIAN & ASIAN food items are dominating the revenue race from with Top 2 places--
 
 
 -- HOURLY SALES ANALYSIS --
 SELECT 
HOUR(order_time) hour,
COUNT(*) items_sold
FROM order_details
GROUP BY hour
ORDER BY items_sold DESC;
/*
     Insight: 
    1. The Sales Rate is higher at mid-day and evening 
    2. The Sales Rate comes down drastically between  mid-day and evening
    3. The Sales Rate is low at Night and mornings
  These are the changes in the sales rate that occur in a single day 
     
     
     */
with dc as(
select COUNT(o.order_details_id) as cnt,Hour(o.order_time) as hourly_sales,m.item_name as item,SUM(m.price) as Total_Revenue
from menu_items m
join order_details o on o.item_id=m.menu_item_id
group by hourly_sales,m.item_name),cf as (
select cnt,hourly_sales,item,Total_revenue,row_number()Over(partition by hourly_sales order by total_revenue desc) as rn
from dc)
select cnt,hourly_sales,item,Total_revenue
from cf
where rn=1
;
/*  Insight:        
During Mid-day Majority of the revenue comes from Korean Beef Bowl & Spaghetti with Meatballs                   

 */
 
-- Average Items Per orders --
SELECT 
COUNT(*) / COUNT(DISTINCT order_id) AS avg_items_per_order
FROM order_details;
-- Insight: The Average items per order is 2.27 items  --



-- Revenue Contribution By Category --
SELECT 
m.category,
SUM(m.price) AS revenue,
ROUND(
SUM(m.price) * 100 / SUM(SUM(m.price)) OVER(),
2
) AS revenue_percentage
FROM menu_items m
JOIN order_details o
ON m.menu_item_id = o.item_id
GROUP BY m.category
ORDER BY revenue DESC;
-- Insight: Majority of the revenue contribution is generated by italian food items with a 31% of the revenue and asian food items with a 29.3% of the revenue  --
